### ISSUE TITLE
Feature Request: Ignore SSL Error

### ISSUE THREAD

**Issue by Sortova** [opennms-forge/onmsblink#13]
We just switched to using a Let's encrypt cert on our OpenNMS instance and now blink won't work.

```
com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.jersey.client.apache.DefaultApacheHttpMethodExecutor.executeMethod(DefaultApacheHttpMethodExecutor.java:213)
	at com.sun.jersey.client.apache.ApacheHttpClientHandler.handle(ApacheHttpClientHandler.java:175)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:692)
	at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:512)
	at org.opennms.onmsblink.OnmsBlink.execute(OnmsBlink.java:280)
	at org.opennms.onmsblink.OnmsBlink.main(OnmsBlink.java:181)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

```
While we are working to get this certificate fixed to work with Java, it would be nice to be able to have an option to ignore SSL errors.

**Comment by pbrane** [comment]
Do you just need to add the certificate to your Java Keystore?

**Comment by Sortova** [comment]
I've had Jesse, Chris and Ben look at it and they can't figure it out. It is something with the intermediate certs, although I'm running the latest Java which is supposed to support all of that.

Also made sure I was running the latest Oracle Java which is supposed to support Let's Encrypt.

**Comment by Sortova** [comment]
Hrm - got it to work by importing the Let's Encrypt Intermediate certs with:
`sudo /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool -trustcacerts -alias letsencrypt -keystore /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts -storepass changeit -noprompt -importcert -file chain.pem`

**Comment by christianpape** [comment]
Added option `--ignore-certificates` to not validate any SSL certificates.
